language: java

jdk:
  - openjdk8
  - openjdk7

# jdk7 build issue "java.security.InvalidKeyException" workaround START
# copied from https://github.com/eseifert/gral/commit/d49d395792c86b9b52f5fa75b1578b6043bf4fd3
sudo: required
before_install:
- sudo wget "https://bouncycastle.org/download/bcprov-ext-jdk15on-158.jar" -O "${JAVA_HOME}/jre/lib/ext/bcprov-ext-jdk15on-158.jar"
- sudo perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/java-7-openjdk/security/java.security
- echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | sudo tee -a /etc/java-7-openjdk/security/java.security
# jdk7 build issue workaround END

env:
- TERM=dumb

after_success:
- ./gradlew jacocoTestReport coveralls